/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package DBMSDemo;

import java.awt.Toolkit;
import java.beans.PropertyVetoException;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JInternalFrame;
import util.GlobalData;

/**
 *
 * @author kelto
 */
public class FormMain extends javax.swing.JFrame {

    /**
     * Creates new form FormMain
     */
    FormLogin formLogin = new FormLogin();
    FormAddCelestialObject formAddco = new FormAddCelestialObject();
    FormViewCelestialObject formViewco = new FormViewCelestialObject();
    FormViewConstellation formViewConstellation = new FormViewConstellation();
    FormViewMainSeq formViewMainSeq = new FormViewMainSeq();
    FormViewSpaceObject formViewSpaceObject = new FormViewSpaceObject();
    FormViewStar formViewStar = new FormViewStar();
    Map<String, JInternalFrame> forms =  new HashMap<>();
            
    
    public FormMain() {
        initComponents();
        forms.put("formLogin", formLogin);
        forms.put("formAddCO", formAddco);
        forms.put("formViewCO", formViewco);
        forms.put("formViewConstellation", formViewConstellation);
        forms.put("formViewMainSeq", formViewMainSeq);
        forms.put("formViewSpaceObject", formViewSpaceObject);
        forms.put("formViewStar", formViewStar);
        
        forms.values().forEach((form) -> {
            jdpContainer.add(form);
        });
    }
    
    private void showForm(String formName) {
        showForm(formName, false);
    }
    
    private void showForm(String formName, boolean checkLogin) {
        if (checkLogin && GlobalData.star == null) {
            showForm("FormLogin", false);
        } else {
            try {
                // Do Authorization
                if (forms.get(formName).isClosed()) {
                    // Create New
                    try {
                        forms.put(formName, forms.get(formName).getClass().newInstance());
                        jdpContainer.add(forms.get(formName));
                        
                    } catch (InstantiationException ex) {
                        Logger.getLogger(FormMain.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (IllegalAccessException ex) {
                        Logger.getLogger(FormMain.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                forms.get(formName).setVisible(true);
                forms.get(formName).setSelected(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(FormMain.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdpContainer = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuFile = new javax.swing.JMenu();
        mniLogin = new javax.swing.JMenuItem();
        mniLogout = new javax.swing.JMenuItem();
        mniExit = new javax.swing.JMenuItem();
        mnuManage = new javax.swing.JMenu();
        mniCO = new javax.swing.JMenu();
        mniAddCO = new javax.swing.JMenuItem();
        mniUpdateCO = new javax.swing.JMenuItem();
        mniDeleteCO = new javax.swing.JMenuItem();
        mniViewCO = new javax.swing.JMenuItem();
        mniC = new javax.swing.JMenu();
        mniAddC = new javax.swing.JMenuItem();
        mniUpdateC = new javax.swing.JMenuItem();
        mniDeleteC = new javax.swing.JMenuItem();
        mniViewC = new javax.swing.JMenuItem();
        mniMS = new javax.swing.JMenu();
        mniAddCO2 = new javax.swing.JMenuItem();
        mniUpdateCO2 = new javax.swing.JMenuItem();
        mniDeleteCO2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        mniSO = new javax.swing.JMenu();
        mniAddCO3 = new javax.swing.JMenuItem();
        mniUpdateCO3 = new javax.swing.JMenuItem();
        mniDeleteCO3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        mniS = new javax.swing.JMenu();
        mniAddCO4 = new javax.swing.JMenuItem();
        mniUpdateCO4 = new javax.swing.JMenuItem();
        mniDeleteCO4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jdpContainerLayout = new javax.swing.GroupLayout(jdpContainer);
        jdpContainer.setLayout(jdpContainerLayout);
        jdpContainerLayout.setHorizontalGroup(
            jdpContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jdpContainerLayout.setVerticalGroup(
            jdpContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );

        getContentPane().add(jdpContainer, java.awt.BorderLayout.CENTER);

        mnuFile.setText("File");

        mniLogin.setText("Login");
        mniLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniLoginActionPerformed(evt);
            }
        });
        mnuFile.add(mniLogin);

        mniLogout.setText("Logout");
        mnuFile.add(mniLogout);

        mniExit.setText("Exit");
        mnuFile.add(mniExit);

        jMenuBar1.add(mnuFile);

        mnuManage.setText("Manage");

        mniCO.setText("CelestialObject");

        mniAddCO.setText("Add");
        mniAddCO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniAddCOActionPerformed(evt);
            }
        });
        mniCO.add(mniAddCO);

        mniUpdateCO.setText("Update");
        mniUpdateCO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniUpdateCOActionPerformed(evt);
            }
        });
        mniCO.add(mniUpdateCO);

        mniDeleteCO.setText("Delete");
        mniDeleteCO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDeleteCOActionPerformed(evt);
            }
        });
        mniCO.add(mniDeleteCO);

        mniViewCO.setText("View");
        mniViewCO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniViewCOActionPerformed(evt);
            }
        });
        mniCO.add(mniViewCO);

        mnuManage.add(mniCO);

        mniC.setText("Constellation");

        mniAddC.setText("Add");
        mniAddC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniAddCActionPerformed(evt);
            }
        });
        mniC.add(mniAddC);

        mniUpdateC.setText("Update");
        mniUpdateC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniUpdateCActionPerformed(evt);
            }
        });
        mniC.add(mniUpdateC);

        mniDeleteC.setText("Delete");
        mniDeleteC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDeleteCActionPerformed(evt);
            }
        });
        mniC.add(mniDeleteC);

        mniViewC.setText("View");
        mniViewC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniViewCActionPerformed(evt);
            }
        });
        mniC.add(mniViewC);

        mnuManage.add(mniC);

        mniMS.setText("MainSeq");

        mniAddCO2.setText("Add");
        mniMS.add(mniAddCO2);

        mniUpdateCO2.setText("Update");
        mniUpdateCO2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniUpdateCO2ActionPerformed(evt);
            }
        });
        mniMS.add(mniUpdateCO2);

        mniDeleteCO2.setText("Delete");
        mniDeleteCO2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDeleteCO2ActionPerformed(evt);
            }
        });
        mniMS.add(mniDeleteCO2);

        jMenuItem3.setText("View");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        mniMS.add(jMenuItem3);

        mnuManage.add(mniMS);

        mniSO.setText("SpaceObject");

        mniAddCO3.setText("Add");
        mniSO.add(mniAddCO3);

        mniUpdateCO3.setText("Update");
        mniUpdateCO3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniUpdateCO3ActionPerformed(evt);
            }
        });
        mniSO.add(mniUpdateCO3);

        mniDeleteCO3.setText("Delete");
        mniDeleteCO3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDeleteCO3ActionPerformed(evt);
            }
        });
        mniSO.add(mniDeleteCO3);

        jMenuItem4.setText("View");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        mniSO.add(jMenuItem4);

        mnuManage.add(mniSO);

        mniS.setText("Star");

        mniAddCO4.setText("Add");
        mniS.add(mniAddCO4);

        mniUpdateCO4.setText("Update");
        mniUpdateCO4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniUpdateCO4ActionPerformed(evt);
            }
        });
        mniS.add(mniUpdateCO4);

        mniDeleteCO4.setText("Delete");
        mniDeleteCO4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDeleteCO4ActionPerformed(evt);
            }
        });
        mniS.add(mniDeleteCO4);

        jMenuItem5.setText("View");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        mniS.add(jMenuItem5);

        mnuManage.add(mniS);

        jMenuBar1.add(mnuManage);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mniLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniLoginActionPerformed
        showForm("formLogin", false);
    }//GEN-LAST:event_mniLoginActionPerformed

    private void mniUpdateCOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniUpdateCOActionPerformed
        showForm("formViewCO");
    }//GEN-LAST:event_mniUpdateCOActionPerformed

    private void mniUpdateCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniUpdateCActionPerformed
        showForm("formViewConstellation");
    }//GEN-LAST:event_mniUpdateCActionPerformed

    private void mniUpdateCO2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniUpdateCO2ActionPerformed
        showForm("formViewMainSeq");
    }//GEN-LAST:event_mniUpdateCO2ActionPerformed

    private void mniUpdateCO3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniUpdateCO3ActionPerformed
        showForm("formViewSpaceObject");
    }//GEN-LAST:event_mniUpdateCO3ActionPerformed

    private void mniUpdateCO4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniUpdateCO4ActionPerformed
        showForm("formViewStar");
    }//GEN-LAST:event_mniUpdateCO4ActionPerformed

    private void mniAddCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniAddCActionPerformed
        
    }//GEN-LAST:event_mniAddCActionPerformed

    private void mniAddCOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniAddCOActionPerformed
        showForm("formAddCO");
    }//GEN-LAST:event_mniAddCOActionPerformed

    private void mniViewCOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniViewCOActionPerformed
        showForm("formViewCO");
    }//GEN-LAST:event_mniViewCOActionPerformed

    private void mniDeleteCOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDeleteCOActionPerformed
        showForm("formViewCO");
    }//GEN-LAST:event_mniDeleteCOActionPerformed

    private void mniViewCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniViewCActionPerformed
        // TODO add your handling code here:
        showForm("formViewConstellation");
    }//GEN-LAST:event_mniViewCActionPerformed

    private void mniDeleteCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDeleteCActionPerformed
        showForm("formViewConstellation");
    }//GEN-LAST:event_mniDeleteCActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        showForm("formViewMainSeq");
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void mniDeleteCO2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDeleteCO2ActionPerformed
        showForm("formViewMainSeq");
    }//GEN-LAST:event_mniDeleteCO2ActionPerformed

    private void mniDeleteCO3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDeleteCO3ActionPerformed
        showForm("formViewSpaceObject");
    }//GEN-LAST:event_mniDeleteCO3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        showForm("formViewSpaceObject");
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void mniDeleteCO4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDeleteCO4ActionPerformed
        showForm("formViewStar");
    }//GEN-LAST:event_mniDeleteCO4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        showForm("formViewStar");
    }//GEN-LAST:event_jMenuItem5ActionPerformed
    
    // End of variables declaration                   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FormMain formMain = new FormMain();
                formMain.setSize(Toolkit.getDefaultToolkit().getScreenSize());
                formMain.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JDesktopPane jdpContainer;
    private javax.swing.JMenuItem mniAddC;
    private javax.swing.JMenuItem mniAddCO;
    private javax.swing.JMenuItem mniAddCO2;
    private javax.swing.JMenuItem mniAddCO3;
    private javax.swing.JMenuItem mniAddCO4;
    private javax.swing.JMenu mniC;
    private javax.swing.JMenu mniCO;
    private javax.swing.JMenuItem mniDeleteC;
    private javax.swing.JMenuItem mniDeleteCO;
    private javax.swing.JMenuItem mniDeleteCO2;
    private javax.swing.JMenuItem mniDeleteCO3;
    private javax.swing.JMenuItem mniDeleteCO4;
    private javax.swing.JMenuItem mniExit;
    private javax.swing.JMenuItem mniLogin;
    private javax.swing.JMenuItem mniLogout;
    private javax.swing.JMenu mniMS;
    private javax.swing.JMenu mniS;
    private javax.swing.JMenu mniSO;
    private javax.swing.JMenuItem mniUpdateC;
    private javax.swing.JMenuItem mniUpdateCO;
    private javax.swing.JMenuItem mniUpdateCO2;
    private javax.swing.JMenuItem mniUpdateCO3;
    private javax.swing.JMenuItem mniUpdateCO4;
    private javax.swing.JMenuItem mniViewC;
    private javax.swing.JMenuItem mniViewCO;
    private javax.swing.JMenu mnuFile;
    private javax.swing.JMenu mnuManage;
    // End of variables declaration//GEN-END:variables
}
