/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package DBMSDemo;

import java.awt.Toolkit;
import java.beans.PropertyVetoException;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JInternalFrame;
import util.GlobalData;

/**
 *
 * @author kelto
 */
public class FormMain extends javax.swing.JFrame {

    /**
     * Creates new form FormMain
     */
    FormLogin formLogin = new FormLogin();
    FormLogout formLogout  = new FormLogout();
    
    FormAddCelestialObject formAddco = new FormAddCelestialObject();
    FormViewCelestialObject formViewco = new FormViewCelestialObject();
    
    FormAddConstellation formAddC = new FormAddConstellation();
    FormViewConstellation formViewC = new FormViewConstellation();
    
    FormAddMainSeq formAddMS = new FormAddMainSeq();
    FormViewMainSeq formViewMS = new FormViewMainSeq();
    
    FormAddSeason formAddSeason = new FormAddSeason();
    FormViewSeason formViewSeason = new FormViewSeason();
    
    FormAddSpaceObject formAddSO = new FormAddSpaceObject();
    FormViewSpaceObject formViewSO = new FormViewSpaceObject();
    
    FormAddStar formAddStar = new FormAddStar();
    FormViewStar formViewStar = new FormViewStar();
    
    Map<String, JInternalFrame> forms =  new HashMap<>();
            
    
    public FormMain() {
        initComponents();
        forms.put("formLogin", formLogin);
        forms.put("formLogout", formLogout);
        
        forms.put("formAddCO", formAddco);
        forms.put("formViewCO", formViewco);
        
        forms.put("formAddC", formAddC);
        forms.put("formViewC", formViewC);
        
        forms.put("formAddMS", formAddMS);
        forms.put("formViewMS", formViewMS);
        
        forms.put("formAddSeason", formAddSeason);
        forms.put("formViewSeason", formViewSeason);
        
        forms.put("formAddSO", formAddSO);
        forms.put("formViewSO", formViewSO);
        
        forms.put("formAddStar", formAddStar);
        forms.put("formViewStar", formViewStar);
        
        forms.values().forEach((form) -> {
            jdpContainer.add(form);
        });
    }
    
    private void showForm(String formName) {
        showForm(formName, false);
    }
    
    private void showForm(String formName, boolean checkLogin) {
        if (checkLogin && GlobalData.stf == null) {
            showForm("FormLogin", false);
        } else {
            try {
                // Do Authorization
                if (forms.get(formName).isClosed()) {
                    // Create New
                    try {
                        forms.put(formName, forms.get(formName).getClass().newInstance());
                        jdpContainer.add(forms.get(formName));
                        
                    } catch (InstantiationException ex) {
                        Logger.getLogger(FormMain.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (IllegalAccessException ex) {
                        Logger.getLogger(FormMain.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                forms.get(formName).setVisible(true);
                forms.get(formName).setSelected(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(FormMain.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdpContainer = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuFile = new javax.swing.JMenu();
        mniLogin = new javax.swing.JMenuItem();
        mniLogout = new javax.swing.JMenuItem();
        mniExit = new javax.swing.JMenuItem();
        mnuManage = new javax.swing.JMenu();
        mniCO = new javax.swing.JMenu();
        mniAddCO = new javax.swing.JMenuItem();
        mniViewCO = new javax.swing.JMenuItem();
        mniC = new javax.swing.JMenu();
        mniAddC = new javax.swing.JMenuItem();
        mniViewC = new javax.swing.JMenuItem();
        mniMS = new javax.swing.JMenu();
        mniAddMS = new javax.swing.JMenuItem();
        mniViewMS = new javax.swing.JMenuItem();
        mniSeason = new javax.swing.JMenu();
        mniAddSeason = new javax.swing.JMenuItem();
        mniViewSeason = new javax.swing.JMenuItem();
        mniSO = new javax.swing.JMenu();
        mniAddSO = new javax.swing.JMenuItem();
        mniViewSO = new javax.swing.JMenuItem();
        mniStar = new javax.swing.JMenu();
        mniAddStar = new javax.swing.JMenuItem();
        mniViewStar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jdpContainerLayout = new javax.swing.GroupLayout(jdpContainer);
        jdpContainer.setLayout(jdpContainerLayout);
        jdpContainerLayout.setHorizontalGroup(
            jdpContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jdpContainerLayout.setVerticalGroup(
            jdpContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );

        getContentPane().add(jdpContainer, java.awt.BorderLayout.CENTER);

        mnuFile.setText("File");

        mniLogin.setText("Login");
        mniLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniLoginActionPerformed(evt);
            }
        });
        mnuFile.add(mniLogin);

        mniLogout.setText("Logout");
        mniLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniLogoutActionPerformed(evt);
            }
        });
        mnuFile.add(mniLogout);

        mniExit.setText("Exit");
        mniExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniExitActionPerformed(evt);
            }
        });
        mnuFile.add(mniExit);

        jMenuBar1.add(mnuFile);

        mnuManage.setText("Manage");

        mniCO.setText("CelestialObject");

        mniAddCO.setText("Add");
        mniAddCO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniAddCOActionPerformed(evt);
            }
        });
        mniCO.add(mniAddCO);

        mniViewCO.setText("View");
        mniViewCO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniViewCOActionPerformed(evt);
            }
        });
        mniCO.add(mniViewCO);

        mnuManage.add(mniCO);

        mniC.setText("Constellation");

        mniAddC.setText("Add");
        mniAddC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniAddCActionPerformed(evt);
            }
        });
        mniC.add(mniAddC);

        mniViewC.setText("View");
        mniViewC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniViewCActionPerformed(evt);
            }
        });
        mniC.add(mniViewC);

        mnuManage.add(mniC);

        mniMS.setText("MainSeq");

        mniAddMS.setText("Add");
        mniAddMS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniAddMSActionPerformed(evt);
            }
        });
        mniMS.add(mniAddMS);

        mniViewMS.setText("View");
        mniViewMS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniViewMSActionPerformed(evt);
            }
        });
        mniMS.add(mniViewMS);

        mnuManage.add(mniMS);

        mniSeason.setText("Season");

        mniAddSeason.setText("Add");
        mniAddSeason.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniAddSeasonActionPerformed(evt);
            }
        });
        mniSeason.add(mniAddSeason);

        mniViewSeason.setText("View");
        mniViewSeason.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniViewSeasonActionPerformed(evt);
            }
        });
        mniSeason.add(mniViewSeason);

        mnuManage.add(mniSeason);

        mniSO.setText("SpaceObject");

        mniAddSO.setText("Add");
        mniAddSO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniAddSOActionPerformed(evt);
            }
        });
        mniSO.add(mniAddSO);

        mniViewSO.setText("View");
        mniViewSO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniViewSOActionPerformed(evt);
            }
        });
        mniSO.add(mniViewSO);

        mnuManage.add(mniSO);

        mniStar.setText("Star");

        mniAddStar.setText("Add");
        mniAddStar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniAddStarActionPerformed(evt);
            }
        });
        mniStar.add(mniAddStar);

        mniViewStar.setText("View");
        mniViewStar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniViewStarActionPerformed(evt);
            }
        });
        mniStar.add(mniViewStar);

        mnuManage.add(mniStar);

        jMenuBar1.add(mnuManage);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mniLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniLoginActionPerformed
        showForm("formLogin", false);
    }//GEN-LAST:event_mniLoginActionPerformed

    private void mniAddCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniAddCActionPerformed
        showForm("formAddC", false);
    }//GEN-LAST:event_mniAddCActionPerformed

    private void mniAddCOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniAddCOActionPerformed
        showForm("formAddCO", false);
    }//GEN-LAST:event_mniAddCOActionPerformed

    private void mniViewCOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniViewCOActionPerformed
        showForm("formViewCO", false);
    }//GEN-LAST:event_mniViewCOActionPerformed

    private void mniViewCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniViewCActionPerformed
        showForm("formViewC", false);
    }//GEN-LAST:event_mniViewCActionPerformed

    private void mniAddSOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniAddSOActionPerformed
        showForm("formAddSO", false);
    }//GEN-LAST:event_mniAddSOActionPerformed

    private void mniViewSOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniViewSOActionPerformed
        showForm("formViewSO", false);
    }//GEN-LAST:event_mniViewSOActionPerformed

    private void mniViewStarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniViewStarActionPerformed
        showForm("formViewStar", false);
    }//GEN-LAST:event_mniViewStarActionPerformed

    private void mniViewSeasonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniViewSeasonActionPerformed
        showForm("formViewSeason", false);
    }//GEN-LAST:event_mniViewSeasonActionPerformed

    private void mniAddMSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniAddMSActionPerformed
        showForm("formAddMS", false);
    }//GEN-LAST:event_mniAddMSActionPerformed

    private void mniViewMSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniViewMSActionPerformed
        showForm("formViewMS", false);
    }//GEN-LAST:event_mniViewMSActionPerformed

    private void mniAddSeasonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniAddSeasonActionPerformed
        showForm("formAddSeason", false);
    }//GEN-LAST:event_mniAddSeasonActionPerformed

    private void mniAddStarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniAddStarActionPerformed
        showForm("formAddStar", false);
    }//GEN-LAST:event_mniAddStarActionPerformed

    private void mniLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniLogoutActionPerformed
        showForm("formLogout", false);
    }//GEN-LAST:event_mniLogoutActionPerformed

    private void mniExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniExitActionPerformed
        this.dispose();
    }//GEN-LAST:event_mniExitActionPerformed
    
    // End of variables declaration                   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FormMain formMain = new FormMain();
                formMain.setSize(Toolkit.getDefaultToolkit().getScreenSize());
                formMain.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JDesktopPane jdpContainer;
    private javax.swing.JMenuItem mniAddC;
    private javax.swing.JMenuItem mniAddCO;
    private javax.swing.JMenuItem mniAddMS;
    private javax.swing.JMenuItem mniAddSO;
    private javax.swing.JMenuItem mniAddSeason;
    private javax.swing.JMenuItem mniAddStar;
    private javax.swing.JMenu mniC;
    private javax.swing.JMenu mniCO;
    private javax.swing.JMenuItem mniExit;
    private javax.swing.JMenuItem mniLogin;
    private javax.swing.JMenuItem mniLogout;
    private javax.swing.JMenu mniMS;
    private javax.swing.JMenu mniSO;
    private javax.swing.JMenu mniSeason;
    private javax.swing.JMenu mniStar;
    private javax.swing.JMenuItem mniViewC;
    private javax.swing.JMenuItem mniViewCO;
    private javax.swing.JMenuItem mniViewMS;
    private javax.swing.JMenuItem mniViewSO;
    private javax.swing.JMenuItem mniViewSeason;
    private javax.swing.JMenuItem mniViewStar;
    private javax.swing.JMenu mnuFile;
    private javax.swing.JMenu mnuManage;
    // End of variables declaration//GEN-END:variables
}
